### ISSUE TITLE
[Feature Request] Editor Requests!

### ISSUE THREAD

**Issue by SuperSaiyajinStackZ** [Universal-Team/LeafEdit#1]
After Version 0.1.0 is released, the work on the Editor will begin!

Do you have some Requests for the Editor? Then post it here.

Current Feature Requests : 
- [ Editing Player Name ] -> 4 Players done.
- [ Tan Editing ] -> Done. Values : 0-15.
- [Villager Editing] -> Villager Changing done.
- [Town Name Editing] -> Done.
- [Acre Editing] -> WIP done.
- [ Town Map Editing ] -> Not Done Yet.
- [Item Viewer] -> Done for Pocket & Dresser.

(This List will be updated with all the Requests, so you can see the current Requests as well!)

**Comment by SuperSaiyajinVoltZ** [comment]
As of Commit https://github.com/Universal-Team/LeafEdit/commit/646cb13eb32f623ef5e7755e66ae208f96494a27  Editing the Player Name [Mayor] is now possible.

**Comment by SuperSaiyajinVoltZ** [comment]
Tan Editing has been implemented as of commit : https://github.com/Universal-Team/LeafEdit/commit/b725e53980ce0a8c0adfb6c7f882c921ded6b598.

**Comment by SuperSaiyajinVoltZ** [comment]
4 Player Editing has been implemented as of commit : https://github.com/Universal-Team/LeafEdit/commit/83b8ce7bca5287b69864fbaf6b36bd58aaab21d7.

**Comment by SuperSaiyajinVoltZ** [comment]
As of the latest Commit : https://github.com/Universal-Team/LeafEdit/commit/71481022a9b2c8b8e84719868c4ea047932199ff

You can edit the following things: 

```
-> Player name.
-> Wallet Amount.
-> Tan Value.
-> Bank Amount.
-> Medal Amount.
-> Coupon Amount.
```

**Comment by SuperSaiyajinVoltZ** [comment]
A Little bit too late, but Villager Editing is now added! [Only changing the Villager though]

More Villager Editing stuff is planned in the future.

**Comment by SuperSaiyajinVoltZ** [comment]
Town Name Editing is added now.

**Comment by SuperSaiyajinVoltZ** [comment]
Acre editing has been implemented with this commit: https://github.com/Universal-Team/LeafEdit/commit/444e4f9dbf3ac737550ff81af276c5ecf8dc2ee1.

**Comment by SuperSaiyajinVoltZ** [comment]
A Pocket Viewer for the Items has been implemented so far with this commit: https://github.com/Universal-Team/LeafEdit/commit/c26790e095b9f251ac2504c82db2e9c34713592e.

Item Editing would be the next part.

**Comment by SuperSaiyajinStackZ** [comment]
Item Viewer for: IslandBox & Storage has been implemented. Also a pattern Viewer & TPC Images.

For the Player Editor: Eye color, Hair Color, Face, Hairstyle can be changed now too.

**Comment by SuperSaiyajinStackZ** [comment]
> Maybe edit the town map? (like in the New Leaf Save Editor)

I have already being worked a bit on it. Here's the current Progress of it: ![img](https://cdn.discordapp.com/attachments/610817877276360734/669728822593323028/unknown.png)

Currently I've been working on Wild World support, so that may take a bit again for the next Progress to the Town Map Editor. 😛

**Comment by SuperSaiyajinStackZ** [comment]
A **Turnip Price Editor** & **Badge Editing** has been implemented in the last time. [I forgot to update this, lul].

Also: Some work on the **Town Map Editor** has been done. (Reading the first 256 Items from the first Acre works as of yet. I continue tomorrow on some next work on it.)

**Comment by SuperSaiyajinStackZ** [comment]
Current New Leaf TODO list:

-  Fix `m_exist[58];` for the Building class.
- Read the other 19 Acre's for the Town Map Editor properly.
- Add Pattern Dumping to `.acnl` format.
- Probably something I forgot.

**Comment by SuperSaiyajinStackZ** [comment]
I close this Issue now, since it can be really confused to read. Please use the other opened Issues if you have a Feature Request for this topic. Thanks.
