### ISSUE TITLE
This feature is not safe!!!

### ISSUE THREAD

**Issue by vexprey01** [Universal-Team/LeafEdit#30]
When I try to use ‘acres’ function in Misc options in Editor in Leaf Edit, it says “This feature is not safe!!! If you like to use this, set ‘Debug’ to true in the config” or something like that. What should I do?

**Comment by SuperSaiyajinStackZ** [comment]
You'd have to edit the `Settings.json` from `sdmc:/LeafEdit/`.

Add `"Debug": true` to the end of the file. Add a `,` to the end of the last Entry.

Example how the config file can look:
```js
{
	"Lang": 1,
	"colorMode": 1,
	"update": true,
	"updateCheck": true,
	"Debug": true
}
``` 

Fair Warning: It can break your save easilly, so it's not recommended!

**Comment by vexprey01** [comment]
Ok but how. Like what should I do on my pc and with what program?

Il giorno dom 1 mar 2020 alle 23:32 StackZ <notifications@github.com> ha
scritto:

**Comment by SuperSaiyajinStackZ** [comment]
You can use Notepad or whatever Text Editor program you have.

**Comment by SuperSaiyajinStackZ** [comment]
You basically just add `"Debug": true` to the file, but add a `,` at the end from `"updateCheck": true/false` before, so it's a valid JSON file then. I'd suggest to join the discord Server for further support: https://discord.gg/KDJCfGF.
